[package]
name = "rust-code"
version = "0.1.0"
authors = ["fuzuchang <fuzuchang@hotmail.com>"]

[dependencies]
time = "0.1.35"

[[bin]]
name="p_str"
path="src/bin/practice-string.rs"
[[bin]]
name="rust-code"
path="src/main.rs"
